### ISSUE TITLE
highlight multi-row string literal

### ISSUE THREAD

**Issue by RomulT** [GoldMax/QtCreatorD#5]
string xx = "
         sdad
         asdas
         dasda
         adsd";
![snapshot1](https://f.cloud.github.com/assets/3272496/1266939/89071676-2c9f-11e3-978a-7cb13bcea88a.png)

**Comment by GoldMax** [comment]
Work as C++ 
`
string x = "ccc"   
    "vvv"   
    "bbb";
`
